model_name: OpenGVLab/InternVL2_5-4B
ssm_layers: [0, 4, 8, 12, 16, 20, 24, 28, 32]
kl_weight: 1
tl_weight: 1
sl_weight: 0
output_hidden_states: true
ce_weight: 0
do_eval: false
tune_mlp: true
tl_loss_type: l2
loss_type: kl
temperature: 1.0
output_dir: output/MaTVLM_0_25_Mamba2_InternVL_4B
seed: 42
save_steps: 4000
warmup_steps: 64000
decay_steps: 64000
per_device_train_batch_size: 1
per_device_eval_batch_size: 4
num_train_epochs: 1
gradient_accumulation_steps: 64
lr_scheduler_type: warmup_stable_decay
optim: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.95
learning_rate: 2.0e-4
weight_decay: 1.0e-2
max_grad_norm: 0.1
# data args
gradient_checkpointing: true
conv_style: internvl2_5
model_max_length: 2048
use_fast_tokenizer: false
force_image_size: 448
max_dynamic_patch: 6
down_sample_ratio: 0.5
drop_path_rate: 0.1
vision_select_layer: -1
dynamic_image_size: true
use_thumbnail: true
ps_version: v2
meta_path: mamba2_internvl/data.json